### ISSUE TITLE
Content Epic

### ISSUE THREAD

**Issue by ferminhg** [ferminhg/demo-repo-to-manage-using-gh#1]
**Description**

- Hous/ROI: 1
- Hours: 20

**Attachments**
[USA states map with labels](https://www.react-simple-maps.io/examples/usa-with-state-labels/)
[react-usa-map](https://www.npmjs.com/package/react-usa-map)

**Checklist**
- [x] merge functions
- [x] merge job titiles
- [x] deploy new content - MVP
- [x] update sitemap - MVP
- [x] setup ahrefs crawl - MVP
- [x] remove non-canonicals from sitemap - MVP
- [x] industryPage: use pertinent industrySlug on jobtitle links
- [x] og:image of every page
- [x] incrementally add ssr back
- [x] resume templates landing page
- [x] links to job title and industry pages from blog page "related content" section
- [x] analyze & fix ahrefs crawl issues - MVP
- [x] content group tracking in GA
- [x] industryPage: more content for conversion
- [ ] create occupations page
- [ ] create /examples
- [ ] create /templates (probably need more templates)
- [ ] create canonical
- [ ] create /salaries (see maps)
- [ ] get more field of studies
- [ ] get more job titles
- [ ] get translateed content
- [ ] get salaries
- [ ] create ability to edit job titles in engine, excel?
- [ ] fix search
- [ ] resume templates landing page
- [ ] reduce number of seeds for images
