### ISSUE TITLE
Free resume builder

### ISSUE THREAD

**Issue by ferminhg** [ferminhg/demo-repo-to-manage-using-gh#3]
**Description**

- Hours / ROI: 1
- Hours: 12
- Impact: 12

**Checklist**
- [ ] Coupons can be applied at time of pricing / totaling
- [ ] Coupons can be tied to products
- [ ] Coupons can expire
- [ ] Coupon can have precedence
- [ ] Coupons have a name
- [ ] Totaling includes coupon, stripe balance, internal balance, products and referrals
- [ ] Add an item
