### ISSUE TITLE
Builder Improvements

### ISSUE THREAD

**Issue by ferminhg** [ferminhg/demo-repo-to-manage-using-gh#4]
**Description**

- Hours / ROI: 0.6
- Hours: 20
- Impact: 30

**Checklist**
- [x] Auth Header
- [x] if no user and one is required prompt login
- [ ] Tips
- [ ] Redo copy
- [x] Rename
- [ ] rename section
- [ ] Change template
- [ ] formatting throughout
- [ ] Revisit content for each step
- [ ] undo changes to template
- [ ] template editor across all steps
- [ ] modal at download popup (choose format)
- [ ] upload resume page (coming soon modal)
- [ ] step validation popups
- [ ] filter content suggestions
- [ ] single page editor (with modals)
- [ ] design cues from resume.io
- [ ] Simple first steps
- [ ] remove links from editor?
- [ ] choose number of columns in details
- [ ] validation: grammar
- [ ] validation: spellchecking
- [ ] validation: gap check
- [ ] validation: resume score
- [ ] validation: sentiment analysis
- [ ] validation: work hiustory / education order
- [ ] trim text input
- [ ] Ignite: fewer choices at template chooser
- [ ] Ignite: pre select in builder, based on experience, school
- [ ] Ignite: multi-step format on resume builder
- [ ] Ignite: fewer template recommendations
- [ ] Add an item
